# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
PUT http://localhost:8000/schedules
Content-Type: application/json
#Content-Type: application/x-www-form-urlencoded

{
  "cron": "*/10 * * * * *",
  "spider_id": "5d2ead494bdee04810bb7654"
}

### cron=*/10 * * * * *&spider_id=5d2ead494bdee04810bb7654

DELETE http://localhost:8000/schedules/5d31b5334bdee082f6e69e7a

###

DELETE http://localhost:8000/spiders/5d31a6ed4bdee07b25d70c7b

###


###

PUT http://localhost:8000/tasks
Content-Type: application/json

{
  "spider_id": "5d32f20f4bdee0f4aae526de",
  "node_id": "5d3343cc4bdee01cb772883e"
}

###

POST http://localhost:8000/spiders/5d32ad224bdee0a60ee5639c/publish

###

POST http://localhost:8000/spiders

###

GET http://localhost:8000/tasks/bb79ec82-1e8f-41c4-858a-5cb682396409/log

###
