FROM node:8.16.0 AS frontend-build

ADD ./frontend /app
WORKDIR /app

# install frontend
RUN npm install -g yarn && yarn install --registry=https://registry.npm.taobao.org

RUN npm run build:prod

FROM alpine:latest

# 安装nginx
RUN mkdir /run/nginx && apk add nginx

# 拷贝编译文件
COPY --from=frontend-build /app/dist /app/dist

# 拷贝nginx代理文件
COPY crawlab.conf /etc/nginx/conf.d

# 拷贝执行脚本
COPY docker_init.sh /app/docker_init.sh

EXPOSE 8080

CMD ["/bin/sh", "/app/docker_init.sh"]