// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.20.1
// source: entity/model_service_v2_request.proto

package grpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ModelServiceV2GetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ModelServiceV2GetByIdRequest) Reset() {
	*x = ModelServiceV2GetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2GetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2GetByIdRequest) ProtoMessage() {}

func (x *ModelServiceV2GetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2GetByIdRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2GetByIdRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{0}
}

func (x *ModelServiceV2GetByIdRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2GetByIdRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2GetByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ModelServiceV2GetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey     string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType   string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query       []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	FindOptions []byte `protobuf:"bytes,4,opt,name=find_options,json=findOptions,proto3" json:"find_options,omitempty"`
}

func (x *ModelServiceV2GetOneRequest) Reset() {
	*x = ModelServiceV2GetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2GetOneRequest) ProtoMessage() {}

func (x *ModelServiceV2GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2GetOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2GetOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{1}
}

func (x *ModelServiceV2GetOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2GetOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2GetOneRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceV2GetOneRequest) GetFindOptions() []byte {
	if x != nil {
		return x.FindOptions
	}
	return nil
}

type ModelServiceV2GetManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey     string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType   string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query       []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	FindOptions []byte `protobuf:"bytes,4,opt,name=find_options,json=findOptions,proto3" json:"find_options,omitempty"`
}

func (x *ModelServiceV2GetManyRequest) Reset() {
	*x = ModelServiceV2GetManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2GetManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2GetManyRequest) ProtoMessage() {}

func (x *ModelServiceV2GetManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2GetManyRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2GetManyRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{2}
}

func (x *ModelServiceV2GetManyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2GetManyRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2GetManyRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceV2GetManyRequest) GetFindOptions() []byte {
	if x != nil {
		return x.FindOptions
	}
	return nil
}

type ModelServiceV2DeleteByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ModelServiceV2DeleteByIdRequest) Reset() {
	*x = ModelServiceV2DeleteByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2DeleteByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2DeleteByIdRequest) ProtoMessage() {}

func (x *ModelServiceV2DeleteByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2DeleteByIdRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2DeleteByIdRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{3}
}

func (x *ModelServiceV2DeleteByIdRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2DeleteByIdRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2DeleteByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ModelServiceV2DeleteOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ModelServiceV2DeleteOneRequest) Reset() {
	*x = ModelServiceV2DeleteOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2DeleteOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2DeleteOneRequest) ProtoMessage() {}

func (x *ModelServiceV2DeleteOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2DeleteOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2DeleteOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{4}
}

func (x *ModelServiceV2DeleteOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2DeleteOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2DeleteOneRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type ModelServiceV2DeleteManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ModelServiceV2DeleteManyRequest) Reset() {
	*x = ModelServiceV2DeleteManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2DeleteManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2DeleteManyRequest) ProtoMessage() {}

func (x *ModelServiceV2DeleteManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2DeleteManyRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2DeleteManyRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{5}
}

func (x *ModelServiceV2DeleteManyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2DeleteManyRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2DeleteManyRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type ModelServiceV2UpdateByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Update    []byte `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *ModelServiceV2UpdateByIdRequest) Reset() {
	*x = ModelServiceV2UpdateByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2UpdateByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2UpdateByIdRequest) ProtoMessage() {}

func (x *ModelServiceV2UpdateByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2UpdateByIdRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2UpdateByIdRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{6}
}

func (x *ModelServiceV2UpdateByIdRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2UpdateByIdRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2UpdateByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelServiceV2UpdateByIdRequest) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

type ModelServiceV2UpdateOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Update    []byte `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *ModelServiceV2UpdateOneRequest) Reset() {
	*x = ModelServiceV2UpdateOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2UpdateOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2UpdateOneRequest) ProtoMessage() {}

func (x *ModelServiceV2UpdateOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2UpdateOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2UpdateOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{7}
}

func (x *ModelServiceV2UpdateOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2UpdateOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2UpdateOneRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceV2UpdateOneRequest) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

type ModelServiceV2UpdateManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Update    []byte `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *ModelServiceV2UpdateManyRequest) Reset() {
	*x = ModelServiceV2UpdateManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2UpdateManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2UpdateManyRequest) ProtoMessage() {}

func (x *ModelServiceV2UpdateManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2UpdateManyRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2UpdateManyRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{8}
}

func (x *ModelServiceV2UpdateManyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2UpdateManyRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2UpdateManyRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceV2UpdateManyRequest) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

type ModelServiceV2ReplaceByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Model     []byte `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *ModelServiceV2ReplaceByIdRequest) Reset() {
	*x = ModelServiceV2ReplaceByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2ReplaceByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2ReplaceByIdRequest) ProtoMessage() {}

func (x *ModelServiceV2ReplaceByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2ReplaceByIdRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2ReplaceByIdRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{9}
}

func (x *ModelServiceV2ReplaceByIdRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2ReplaceByIdRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2ReplaceByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelServiceV2ReplaceByIdRequest) GetModel() []byte {
	if x != nil {
		return x.Model
	}
	return nil
}

type ModelServiceV2ReplaceOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Model     []byte `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *ModelServiceV2ReplaceOneRequest) Reset() {
	*x = ModelServiceV2ReplaceOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2ReplaceOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2ReplaceOneRequest) ProtoMessage() {}

func (x *ModelServiceV2ReplaceOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2ReplaceOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2ReplaceOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{10}
}

func (x *ModelServiceV2ReplaceOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2ReplaceOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2ReplaceOneRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceV2ReplaceOneRequest) GetModel() []byte {
	if x != nil {
		return x.Model
	}
	return nil
}

type ModelServiceV2InsertOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Model     []byte `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *ModelServiceV2InsertOneRequest) Reset() {
	*x = ModelServiceV2InsertOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2InsertOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2InsertOneRequest) ProtoMessage() {}

func (x *ModelServiceV2InsertOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2InsertOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2InsertOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{11}
}

func (x *ModelServiceV2InsertOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2InsertOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2InsertOneRequest) GetModel() []byte {
	if x != nil {
		return x.Model
	}
	return nil
}

type ModelServiceV2InsertManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Models    []byte `protobuf:"bytes,3,opt,name=models,proto3" json:"models,omitempty"`
}

func (x *ModelServiceV2InsertManyRequest) Reset() {
	*x = ModelServiceV2InsertManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2InsertManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2InsertManyRequest) ProtoMessage() {}

func (x *ModelServiceV2InsertManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2InsertManyRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2InsertManyRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{12}
}

func (x *ModelServiceV2InsertManyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2InsertManyRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2InsertManyRequest) GetModels() []byte {
	if x != nil {
		return x.Models
	}
	return nil
}

type ModelServiceV2CountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ModelServiceV2CountRequest) Reset() {
	*x = ModelServiceV2CountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_v2_request_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceV2CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceV2CountRequest) ProtoMessage() {}

func (x *ModelServiceV2CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_v2_request_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceV2CountRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceV2CountRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_v2_request_proto_rawDescGZIP(), []int{13}
}

func (x *ModelServiceV2CountRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceV2CountRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceV2CountRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

var File_entity_model_service_v2_request_proto protoreflect.FileDescriptor

var file_entity_model_service_v2_request_proto_rawDesc = []byte{
	0x0a, 0x25, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x32, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x68, 0x0a,
	0x1c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x1b, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x64, 0x5f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x66,
	0x69, 0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x1c, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x66,
	0x69, 0x6e, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x6b,
	0x0a, 0x1f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x1e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x71, 0x0a,
	0x1f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x22, 0x83, 0x01, 0x0a, 0x1f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x56, 0x32, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x1e, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x89, 0x01, 0x0a, 0x1f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x56, 0x32, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x82, 0x01,
	0x0a, 0x20, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32,
	0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x22, 0x87, 0x01, 0x0a, 0x1f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x56, 0x32, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x70, 0x0a, 0x1e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x73,
	0x0a, 0x1f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x32,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x22, 0x6c, 0x0a, 0x1a, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x56, 0x32, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_entity_model_service_v2_request_proto_rawDescOnce sync.Once
	file_entity_model_service_v2_request_proto_rawDescData = file_entity_model_service_v2_request_proto_rawDesc
)

func file_entity_model_service_v2_request_proto_rawDescGZIP() []byte {
	file_entity_model_service_v2_request_proto_rawDescOnce.Do(func() {
		file_entity_model_service_v2_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_model_service_v2_request_proto_rawDescData)
	})
	return file_entity_model_service_v2_request_proto_rawDescData
}

var file_entity_model_service_v2_request_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_entity_model_service_v2_request_proto_goTypes = []interface{}{
	(*ModelServiceV2GetByIdRequest)(nil),     // 0: grpc.ModelServiceV2GetByIdRequest
	(*ModelServiceV2GetOneRequest)(nil),      // 1: grpc.ModelServiceV2GetOneRequest
	(*ModelServiceV2GetManyRequest)(nil),     // 2: grpc.ModelServiceV2GetManyRequest
	(*ModelServiceV2DeleteByIdRequest)(nil),  // 3: grpc.ModelServiceV2DeleteByIdRequest
	(*ModelServiceV2DeleteOneRequest)(nil),   // 4: grpc.ModelServiceV2DeleteOneRequest
	(*ModelServiceV2DeleteManyRequest)(nil),  // 5: grpc.ModelServiceV2DeleteManyRequest
	(*ModelServiceV2UpdateByIdRequest)(nil),  // 6: grpc.ModelServiceV2UpdateByIdRequest
	(*ModelServiceV2UpdateOneRequest)(nil),   // 7: grpc.ModelServiceV2UpdateOneRequest
	(*ModelServiceV2UpdateManyRequest)(nil),  // 8: grpc.ModelServiceV2UpdateManyRequest
	(*ModelServiceV2ReplaceByIdRequest)(nil), // 9: grpc.ModelServiceV2ReplaceByIdRequest
	(*ModelServiceV2ReplaceOneRequest)(nil),  // 10: grpc.ModelServiceV2ReplaceOneRequest
	(*ModelServiceV2InsertOneRequest)(nil),   // 11: grpc.ModelServiceV2InsertOneRequest
	(*ModelServiceV2InsertManyRequest)(nil),  // 12: grpc.ModelServiceV2InsertManyRequest
	(*ModelServiceV2CountRequest)(nil),       // 13: grpc.ModelServiceV2CountRequest
}
var file_entity_model_service_v2_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_model_service_v2_request_proto_init() }
func file_entity_model_service_v2_request_proto_init() {
	if File_entity_model_service_v2_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_model_service_v2_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2GetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2GetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2GetManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2DeleteByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2DeleteOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2DeleteManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2UpdateByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2UpdateOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2UpdateManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2ReplaceByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2ReplaceOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2InsertOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2InsertManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_v2_request_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelServiceV2CountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_model_service_v2_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_model_service_v2_request_proto_goTypes,
		DependencyIndexes: file_entity_model_service_v2_request_proto_depIdxs,
		MessageInfos:      file_entity_model_service_v2_request_proto_msgTypes,
	}.Build()
	File_entity_model_service_v2_request_proto = out.File
	file_entity_model_service_v2_request_proto_rawDesc = nil
	file_entity_model_service_v2_request_proto_goTypes = nil
	file_entity_model_service_v2_request_proto_depIdxs = nil
}
