// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: entity/model_service_request.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelServiceGetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ModelServiceGetByIdRequest) Reset() {
	*x = ModelServiceGetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceGetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceGetByIdRequest) ProtoMessage() {}

func (x *ModelServiceGetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceGetByIdRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceGetByIdRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{0}
}

func (x *ModelServiceGetByIdRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceGetByIdRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceGetByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ModelServiceGetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey     string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType   string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query       []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	FindOptions []byte `protobuf:"bytes,4,opt,name=find_options,json=findOptions,proto3" json:"find_options,omitempty"`
}

func (x *ModelServiceGetOneRequest) Reset() {
	*x = ModelServiceGetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceGetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceGetOneRequest) ProtoMessage() {}

func (x *ModelServiceGetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceGetOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceGetOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{1}
}

func (x *ModelServiceGetOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceGetOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceGetOneRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceGetOneRequest) GetFindOptions() []byte {
	if x != nil {
		return x.FindOptions
	}
	return nil
}

type ModelServiceGetManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey     string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType   string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query       []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	FindOptions []byte `protobuf:"bytes,4,opt,name=find_options,json=findOptions,proto3" json:"find_options,omitempty"`
}

func (x *ModelServiceGetManyRequest) Reset() {
	*x = ModelServiceGetManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceGetManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceGetManyRequest) ProtoMessage() {}

func (x *ModelServiceGetManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceGetManyRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceGetManyRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{2}
}

func (x *ModelServiceGetManyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceGetManyRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceGetManyRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceGetManyRequest) GetFindOptions() []byte {
	if x != nil {
		return x.FindOptions
	}
	return nil
}

type ModelServiceDeleteByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ModelServiceDeleteByIdRequest) Reset() {
	*x = ModelServiceDeleteByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceDeleteByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceDeleteByIdRequest) ProtoMessage() {}

func (x *ModelServiceDeleteByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceDeleteByIdRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceDeleteByIdRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{3}
}

func (x *ModelServiceDeleteByIdRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceDeleteByIdRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceDeleteByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ModelServiceDeleteOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ModelServiceDeleteOneRequest) Reset() {
	*x = ModelServiceDeleteOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceDeleteOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceDeleteOneRequest) ProtoMessage() {}

func (x *ModelServiceDeleteOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceDeleteOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceDeleteOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{4}
}

func (x *ModelServiceDeleteOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceDeleteOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceDeleteOneRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type ModelServiceDeleteManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ModelServiceDeleteManyRequest) Reset() {
	*x = ModelServiceDeleteManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceDeleteManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceDeleteManyRequest) ProtoMessage() {}

func (x *ModelServiceDeleteManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceDeleteManyRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceDeleteManyRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{5}
}

func (x *ModelServiceDeleteManyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceDeleteManyRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceDeleteManyRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type ModelServiceUpdateByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Update    []byte `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *ModelServiceUpdateByIdRequest) Reset() {
	*x = ModelServiceUpdateByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceUpdateByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceUpdateByIdRequest) ProtoMessage() {}

func (x *ModelServiceUpdateByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceUpdateByIdRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceUpdateByIdRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{6}
}

func (x *ModelServiceUpdateByIdRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceUpdateByIdRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceUpdateByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelServiceUpdateByIdRequest) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

type ModelServiceUpdateOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Update    []byte `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *ModelServiceUpdateOneRequest) Reset() {
	*x = ModelServiceUpdateOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceUpdateOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceUpdateOneRequest) ProtoMessage() {}

func (x *ModelServiceUpdateOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceUpdateOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceUpdateOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{7}
}

func (x *ModelServiceUpdateOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceUpdateOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceUpdateOneRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceUpdateOneRequest) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

type ModelServiceUpdateManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Update    []byte `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *ModelServiceUpdateManyRequest) Reset() {
	*x = ModelServiceUpdateManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceUpdateManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceUpdateManyRequest) ProtoMessage() {}

func (x *ModelServiceUpdateManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceUpdateManyRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceUpdateManyRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{8}
}

func (x *ModelServiceUpdateManyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceUpdateManyRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceUpdateManyRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceUpdateManyRequest) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

type ModelServiceReplaceByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Model     []byte `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *ModelServiceReplaceByIdRequest) Reset() {
	*x = ModelServiceReplaceByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceReplaceByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceReplaceByIdRequest) ProtoMessage() {}

func (x *ModelServiceReplaceByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceReplaceByIdRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceReplaceByIdRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{9}
}

func (x *ModelServiceReplaceByIdRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceReplaceByIdRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceReplaceByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelServiceReplaceByIdRequest) GetModel() []byte {
	if x != nil {
		return x.Model
	}
	return nil
}

type ModelServiceReplaceOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Model     []byte `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *ModelServiceReplaceOneRequest) Reset() {
	*x = ModelServiceReplaceOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceReplaceOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceReplaceOneRequest) ProtoMessage() {}

func (x *ModelServiceReplaceOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceReplaceOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceReplaceOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{10}
}

func (x *ModelServiceReplaceOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceReplaceOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceReplaceOneRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ModelServiceReplaceOneRequest) GetModel() []byte {
	if x != nil {
		return x.Model
	}
	return nil
}

type ModelServiceInsertOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Model     []byte `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *ModelServiceInsertOneRequest) Reset() {
	*x = ModelServiceInsertOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceInsertOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceInsertOneRequest) ProtoMessage() {}

func (x *ModelServiceInsertOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceInsertOneRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceInsertOneRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{11}
}

func (x *ModelServiceInsertOneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceInsertOneRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceInsertOneRequest) GetModel() []byte {
	if x != nil {
		return x.Model
	}
	return nil
}

type ModelServiceInsertManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Models    []byte `protobuf:"bytes,3,opt,name=models,proto3" json:"models,omitempty"`
}

func (x *ModelServiceInsertManyRequest) Reset() {
	*x = ModelServiceInsertManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceInsertManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceInsertManyRequest) ProtoMessage() {}

func (x *ModelServiceInsertManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceInsertManyRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceInsertManyRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{12}
}

func (x *ModelServiceInsertManyRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceInsertManyRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceInsertManyRequest) GetModels() []byte {
	if x != nil {
		return x.Models
	}
	return nil
}

type ModelServiceCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey   string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Query     []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ModelServiceCountRequest) Reset() {
	*x = ModelServiceCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_model_service_request_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelServiceCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceCountRequest) ProtoMessage() {}

func (x *ModelServiceCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_model_service_request_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceCountRequest.ProtoReflect.Descriptor instead.
func (*ModelServiceCountRequest) Descriptor() ([]byte, []int) {
	return file_entity_model_service_request_proto_rawDescGZIP(), []int{13}
}

func (x *ModelServiceCountRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *ModelServiceCountRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelServiceCountRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

var File_entity_model_service_request_proto protoreflect.FileDescriptor

var file_entity_model_service_request_proto_rawDesc = []byte{
	0x0a, 0x22, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x66, 0x0a, 0x1a, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x19, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x1a, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x69, 0x0a, 0x1d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x6e, 0x0a, 0x1c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x22, 0x6f, 0x0a, 0x1d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x22, 0x81, 0x01, 0x0a, 0x1d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x1c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x87,
	0x01, 0x0a, 0x1d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x1e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x85, 0x01, 0x0a, 0x1d,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x6e, 0x0a, 0x1c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x71, 0x0a, 0x1d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x6a, 0x0a, 0x18, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_model_service_request_proto_rawDescOnce sync.Once
	file_entity_model_service_request_proto_rawDescData = file_entity_model_service_request_proto_rawDesc
)

func file_entity_model_service_request_proto_rawDescGZIP() []byte {
	file_entity_model_service_request_proto_rawDescOnce.Do(func() {
		file_entity_model_service_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_model_service_request_proto_rawDescData)
	})
	return file_entity_model_service_request_proto_rawDescData
}

var file_entity_model_service_request_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_entity_model_service_request_proto_goTypes = []any{
	(*ModelServiceGetByIdRequest)(nil),     // 0: grpc.ModelServiceGetByIdRequest
	(*ModelServiceGetOneRequest)(nil),      // 1: grpc.ModelServiceGetOneRequest
	(*ModelServiceGetManyRequest)(nil),     // 2: grpc.ModelServiceGetManyRequest
	(*ModelServiceDeleteByIdRequest)(nil),  // 3: grpc.ModelServiceDeleteByIdRequest
	(*ModelServiceDeleteOneRequest)(nil),   // 4: grpc.ModelServiceDeleteOneRequest
	(*ModelServiceDeleteManyRequest)(nil),  // 5: grpc.ModelServiceDeleteManyRequest
	(*ModelServiceUpdateByIdRequest)(nil),  // 6: grpc.ModelServiceUpdateByIdRequest
	(*ModelServiceUpdateOneRequest)(nil),   // 7: grpc.ModelServiceUpdateOneRequest
	(*ModelServiceUpdateManyRequest)(nil),  // 8: grpc.ModelServiceUpdateManyRequest
	(*ModelServiceReplaceByIdRequest)(nil), // 9: grpc.ModelServiceReplaceByIdRequest
	(*ModelServiceReplaceOneRequest)(nil),  // 10: grpc.ModelServiceReplaceOneRequest
	(*ModelServiceInsertOneRequest)(nil),   // 11: grpc.ModelServiceInsertOneRequest
	(*ModelServiceInsertManyRequest)(nil),  // 12: grpc.ModelServiceInsertManyRequest
	(*ModelServiceCountRequest)(nil),       // 13: grpc.ModelServiceCountRequest
}
var file_entity_model_service_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_model_service_request_proto_init() }
func file_entity_model_service_request_proto_init() {
	if File_entity_model_service_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_model_service_request_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceGetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceGetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceGetManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceDeleteByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceDeleteOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceDeleteManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceUpdateByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceUpdateOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceUpdateManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceReplaceByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceReplaceOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceInsertOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceInsertManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_model_service_request_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ModelServiceCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_model_service_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_model_service_request_proto_goTypes,
		DependencyIndexes: file_entity_model_service_request_proto_depIdxs,
		MessageInfos:      file_entity_model_service_request_proto_msgTypes,
	}.Build()
	File_entity_model_service_request_proto = out.File
	file_entity_model_service_request_proto_rawDesc = nil
	file_entity_model_service_request_proto_goTypes = nil
	file_entity_model_service_request_proto_depIdxs = nil
}
