// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: services/task_service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskServiceSubscribeCode int32

const (
	TaskServiceSubscribeCode_CANCEL TaskServiceSubscribeCode = 0
)

// Enum value maps for TaskServiceSubscribeCode.
var (
	TaskServiceSubscribeCode_name = map[int32]string{
		0: "CANCEL",
	}
	TaskServiceSubscribeCode_value = map[string]int32{
		"CANCEL": 0,
	}
)

func (x TaskServiceSubscribeCode) Enum() *TaskServiceSubscribeCode {
	p := new(TaskServiceSubscribeCode)
	*p = x
	return p
}

func (x TaskServiceSubscribeCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskServiceSubscribeCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_task_service_proto_enumTypes[0].Descriptor()
}

func (TaskServiceSubscribeCode) Type() protoreflect.EnumType {
	return &file_services_task_service_proto_enumTypes[0]
}

func (x TaskServiceSubscribeCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskServiceSubscribeCode.Descriptor instead.
func (TaskServiceSubscribeCode) EnumDescriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{0}
}

type TaskServiceConnectCode int32

const (
	TaskServiceConnectCode_INSERT_DATA TaskServiceConnectCode = 0
	TaskServiceConnectCode_INSERT_LOGS TaskServiceConnectCode = 1
)

// Enum value maps for TaskServiceConnectCode.
var (
	TaskServiceConnectCode_name = map[int32]string{
		0: "INSERT_DATA",
		1: "INSERT_LOGS",
	}
	TaskServiceConnectCode_value = map[string]int32{
		"INSERT_DATA": 0,
		"INSERT_LOGS": 1,
	}
)

func (x TaskServiceConnectCode) Enum() *TaskServiceConnectCode {
	p := new(TaskServiceConnectCode)
	*p = x
	return p
}

func (x TaskServiceConnectCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskServiceConnectCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_task_service_proto_enumTypes[1].Descriptor()
}

func (TaskServiceConnectCode) Type() protoreflect.EnumType {
	return &file_services_task_service_proto_enumTypes[1]
}

func (x TaskServiceConnectCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskServiceConnectCode.Descriptor instead.
func (TaskServiceConnectCode) EnumDescriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{1}
}

type TaskServiceSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *TaskServiceSubscribeRequest) Reset() {
	*x = TaskServiceSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_task_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskServiceSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceSubscribeRequest) ProtoMessage() {}

func (x *TaskServiceSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceSubscribeRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskServiceSubscribeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskServiceSubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   TaskServiceSubscribeCode `protobuf:"varint,1,opt,name=code,proto3,enum=grpc.TaskServiceSubscribeCode" json:"code,omitempty"`
	TaskId string                   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Force  bool                     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *TaskServiceSubscribeResponse) Reset() {
	*x = TaskServiceSubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_task_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskServiceSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceSubscribeResponse) ProtoMessage() {}

func (x *TaskServiceSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceSubscribeResponse.ProtoReflect.Descriptor instead.
func (*TaskServiceSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *TaskServiceSubscribeResponse) GetCode() TaskServiceSubscribeCode {
	if x != nil {
		return x.Code
	}
	return TaskServiceSubscribeCode_CANCEL
}

func (x *TaskServiceSubscribeResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskServiceSubscribeResponse) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TaskServiceConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   TaskServiceConnectCode `protobuf:"varint,1,opt,name=code,proto3,enum=grpc.TaskServiceConnectCode" json:"code,omitempty"`
	TaskId string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Data   []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TaskServiceConnectRequest) Reset() {
	*x = TaskServiceConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_task_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskServiceConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceConnectRequest) ProtoMessage() {}

func (x *TaskServiceConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceConnectRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceConnectRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *TaskServiceConnectRequest) GetCode() TaskServiceConnectCode {
	if x != nil {
		return x.Code
	}
	return TaskServiceConnectCode_INSERT_DATA
}

func (x *TaskServiceConnectRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskServiceConnectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskServiceFetchTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
}

func (x *TaskServiceFetchTaskRequest) Reset() {
	*x = TaskServiceFetchTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_task_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskServiceFetchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceFetchTaskRequest) ProtoMessage() {}

func (x *TaskServiceFetchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceFetchTaskRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceFetchTaskRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *TaskServiceFetchTaskRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

type TaskServiceFetchTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *TaskServiceFetchTaskResponse) Reset() {
	*x = TaskServiceFetchTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_task_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskServiceFetchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceFetchTaskResponse) ProtoMessage() {}

func (x *TaskServiceFetchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceFetchTaskResponse.ProtoReflect.Descriptor instead.
func (*TaskServiceFetchTaskResponse) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *TaskServiceFetchTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskServiceSendNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	TaskId  string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *TaskServiceSendNotificationRequest) Reset() {
	*x = TaskServiceSendNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_task_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskServiceSendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceSendNotificationRequest) ProtoMessage() {}

func (x *TaskServiceSendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceSendNotificationRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceSendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *TaskServiceSendNotificationRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *TaskServiceSendNotificationRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_services_task_service_proto protoreflect.FileDescriptor

var file_services_task_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67,
	0x72, 0x70, 0x63, 0x1a, 0x15, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x1b, 0x54, 0x61,
	0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x1c, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x7a, 0x0a, 0x19, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x38, 0x0a, 0x1b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x1c,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x22, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x2a,
	0x26, 0x0a, 0x18, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43,
	0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x00, 0x2a, 0x3a, 0x0a, 0x16, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x5f, 0x44, 0x41, 0x54, 0x41,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x5f, 0x4c, 0x4f, 0x47,
	0x53, 0x10, 0x01, 0x32, 0xcb, 0x02, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x54, 0x0a, 0x09, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4e, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_services_task_service_proto_rawDescOnce sync.Once
	file_services_task_service_proto_rawDescData = file_services_task_service_proto_rawDesc
)

func file_services_task_service_proto_rawDescGZIP() []byte {
	file_services_task_service_proto_rawDescOnce.Do(func() {
		file_services_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_task_service_proto_rawDescData)
	})
	return file_services_task_service_proto_rawDescData
}

var file_services_task_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_services_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_task_service_proto_goTypes = []any{
	(TaskServiceSubscribeCode)(0),              // 0: grpc.TaskServiceSubscribeCode
	(TaskServiceConnectCode)(0),                // 1: grpc.TaskServiceConnectCode
	(*TaskServiceSubscribeRequest)(nil),        // 2: grpc.TaskServiceSubscribeRequest
	(*TaskServiceSubscribeResponse)(nil),       // 3: grpc.TaskServiceSubscribeResponse
	(*TaskServiceConnectRequest)(nil),          // 4: grpc.TaskServiceConnectRequest
	(*TaskServiceFetchTaskRequest)(nil),        // 5: grpc.TaskServiceFetchTaskRequest
	(*TaskServiceFetchTaskResponse)(nil),       // 6: grpc.TaskServiceFetchTaskResponse
	(*TaskServiceSendNotificationRequest)(nil), // 7: grpc.TaskServiceSendNotificationRequest
	(*Response)(nil),                           // 8: grpc.Response
}
var file_services_task_service_proto_depIdxs = []int32{
	0, // 0: grpc.TaskServiceSubscribeResponse.code:type_name -> grpc.TaskServiceSubscribeCode
	1, // 1: grpc.TaskServiceConnectRequest.code:type_name -> grpc.TaskServiceConnectCode
	2, // 2: grpc.TaskService.Subscribe:input_type -> grpc.TaskServiceSubscribeRequest
	4, // 3: grpc.TaskService.Connect:input_type -> grpc.TaskServiceConnectRequest
	5, // 4: grpc.TaskService.FetchTask:input_type -> grpc.TaskServiceFetchTaskRequest
	7, // 5: grpc.TaskService.SendNotification:input_type -> grpc.TaskServiceSendNotificationRequest
	3, // 6: grpc.TaskService.Subscribe:output_type -> grpc.TaskServiceSubscribeResponse
	8, // 7: grpc.TaskService.Connect:output_type -> grpc.Response
	6, // 8: grpc.TaskService.FetchTask:output_type -> grpc.TaskServiceFetchTaskResponse
	8, // 9: grpc.TaskService.SendNotification:output_type -> grpc.Response
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_task_service_proto_init() }
func file_services_task_service_proto_init() {
	if File_services_task_service_proto != nil {
		return
	}
	file_entity_response_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_task_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TaskServiceSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_task_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TaskServiceSubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_task_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TaskServiceConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_task_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TaskServiceFetchTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_task_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TaskServiceFetchTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_task_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TaskServiceSendNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_task_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_task_service_proto_goTypes,
		DependencyIndexes: file_services_task_service_proto_depIdxs,
		EnumInfos:         file_services_task_service_proto_enumTypes,
		MessageInfos:      file_services_task_service_proto_msgTypes,
	}.Build()
	File_services_task_service_proto = out.File
	file_services_task_service_proto_rawDesc = nil
	file_services_task_service_proto_goTypes = nil
	file_services_task_service_proto_depIdxs = nil
}
